version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
  # frontdend:
  #   build: ./front-end/
  #   container_name: front_end
  #   image: front_end
  #   restart: always
  #   ports:
  #       - "3000:3000"
  # backdend:
  #   build: ./back-end/
  #   container_name: back_end
  #   image: back_end
  #   restart: always
  #   ports:
  #       - "3001:3001"